### ISSUE TITLE
Step 1: Create a concept with wireframes

### ISSUE THREAD

**Issue by jossdoe** [jossdoe/todos#1]
Before we start, we should come up with a general concept & structure of the app. Creating wireframes might be good for that. I think, we should consider focussing on the mobile view first, since that's probably the main use-case for Todo apps.

Basic requirements as stated in the assignment are:
* Ability to create Todo-items
* Ability to mark items as done
* Ability to edit Todo entries

Additional feature idea:
* Ability to delete single/all items from the list

**Comment by jossdoe** [comment]
We got started on the wireframes: https://www.figma.com/file/oC7IuZaazF4Cm5QQgJahqH/Untitled?node-id=0%3A1

**Comment by rb-wbscoding** [comment]
I think we have done this and too me at least it looks good
