### ISSUE TITLE
JS & DOM: Create a function that deletes a specific Todo-item from the list (with confirmation)

### ISSUE THREAD

**Issue by jossdoe** [jossdoe/todos#7]
We could add a functionality to delete a specific Todo-item from the app. UX-wise it might be good to consider putting in a confirmation step for this, so the user doesn't delete anything by accident.

The code for the confirmation step can be combined with the confirmation step of Issue #8.

**Comment by rb-wbscoding** [comment]
I think we also discussed this, yes a confirmation is vital (or swipe right)
