### ISSUE TITLE
JS & DOM: Create a function that clears all Todo-items from the list (with confirmation)

### ISSUE THREAD

**Issue by jossdoe** [jossdoe/todos#8]
We could add a functionality to clear the whole Todo list with one action. UX-wise it might be good to consider putting in a confirmation step for this, so the user doesn't delete anything by accident.

The code for the confirmation step can be combined with the confirmation step of Issue #7.

**Comment by rb-wbscoding** [comment]
Maybe, for e-mail websites these are often located in the bar above the actual emails. Not sure if this is a core feature, maybe if there is time  (could also be part of the drop down menu)
